// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKwSNuFZIE-tJ_YsaImRfX6Va-WfEaujw',
    appId: '1:936070815257:web:0f60197536e90eefcdd488',
    messagingSenderId: '936070815257',
    projectId: 'crud-461f7',
    authDomain: 'crud-461f7.firebaseapp.com',
    storageBucket: 'crud-461f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcXuVMPOGEvi3CYOoicmINgG-xw1-6SXY',
    appId: '1:936070815257:android:41cdd1dc7da815fdcdd488',
    messagingSenderId: '936070815257',
    projectId: 'crud-461f7',
    storageBucket: 'crud-461f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVNSn5L_74J13MhX1JXxnyNBhLWcHJMSw',
    appId: '1:936070815257:ios:08296aaa770e57afcdd488',
    messagingSenderId: '936070815257',
    projectId: 'crud-461f7',
    storageBucket: 'crud-461f7.appspot.com',
    iosClientId: '936070815257-g8q689a91u5gha5klcua0utn8gti6jhe.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVNSn5L_74J13MhX1JXxnyNBhLWcHJMSw',
    appId: '1:936070815257:ios:285a733cc677c5d1cdd488',
    messagingSenderId: '936070815257',
    projectId: 'crud-461f7',
    storageBucket: 'crud-461f7.appspot.com',
    iosClientId: '936070815257-r42c9iqegfmdc94odohvn3ktt30j1s6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterApi.RunnerTests',
  );
}
